mtcars
x5=c(1:10)
(x5=c(1:10))
(mean(x5))
(median(x5))
(mymatrix=matrix(1:24,ncol=6,b
?length
?length
mymatrix[,1]                 
colSums(mymatrix)
rowMeans(mymatrix)
marks=rnorm(60,mean=60,sd=10)
(marks)
plot(density(marks))
matrix(marks,ncol=6)
?matrix
(myarray=array(1:24,dim=c(4,3,2)))
colSums(myarray)
apply(myarray,1,sum)
?array
?array

read.csv('./data/Data-8a.csv')
dt=read.csv('./data/Data-8a.csv')
head(dt)
head(dt)
df1=read.csv(file=file.choose())
write.csv(mtcars,file='./data/mtcars.csv')
